### ISSUE TITLE
Missing tables

### ISSUE THREAD

**Issue by jeppe742** [shokru/mlfactor.github.io#49]
Hey @shokru, 
while reading through chapter 4, I noticed that there seemed to be some broken equation and table links. I have found the following:
- 4.2.5: "We then reformat these betas from Table ??"
- 4.2.6: "We obtain the vector of  α  values from Equation ()"
- 4.2.6: Is there supposed to be a table of the p-values from the regression?
- 5.8: "..the first estimation for the cap coefficient is above 5% (in Table ??)"
- 16.1: "..many variables are used in the regression below (Table ??)

Besides this, your work has been very well written and interesting so far :+1:

**Comment by shokru** [comment]
Dear Jeppe,
thank you very much for your feedback. You are right.
I have to prepare the final version for the editor and I'm facing trouble making the pdf version AND the html one work at the same time.
I've corrected the issues for chapter 4. It's not perfect (the ?? are still there), but at least the tables appear.
I will continue progressively. The online version will be continuously updated. 
Please notify me if anything seems suspicious.
Thanks again.

**Comment by jeppe742** [comment]
Thanks for the quick fix. I will close the issue for now
