### ISSUE TITLE
PDF page 404

### ISSUE THREAD

**Issue by rmwever** [shokru/mlfactor.github.io#50]
Hi @shokru, thanks for making this awesome resource available on the web!

FYI, I'm trying to download the PDF button, which links to http://www.mlfactor.com/ML_factor.pdf, but I'm receiving a 404 error.

**Comment by shokru** [comment]
Dear Ryan,
thank you for the warning. Where exactly is this button located?
The book is available in html format but not in pdf version (my publisher is already kind enough :)).
This is why I'm surprised about this button...

**Comment by rmwever** [comment]
Ah ok oops!

The PDF button is up in the navbar, on the right hand side:
![image](https://user-images.githubusercontent.com/4733652/83092607-3e794c80-a0d0-11ea-91f8-2e0fb965e403.png)

**Comment by shokru** [comment]
Thank you!
I never realized it even existed.
I removed it in the lastest version.

**Comment by rmwever** [comment]
No problem 👍🏻
