### ISSUE TITLE
Potential Typo

### ISSUE THREAD

**Issue by xianglu96** [shokru/mlfactor.github.io#51]
Very informative book!

In chpt 4.2.3, 
Value (HM = high minus low: undervalued minus `growth’ firms): Fama and French (1992), Fama and French (1993), C. S. Asness, Moskowitz, and Pedersen (2013).

Should this 'HM' be 'HML'?

**Comment by shokru** [comment]
Thank you!
Yes, you are right.
I just corrected the typo.
