### ISSUE TITLE
Chapter 3.2.4 - errata

### ISSUE THREAD

**Issue by csrvermaak** [shokru/mlfactor.github.io#53]
I suspect a sub-chapter has gone "missing" due to a missing {Enter} \newline - both in the hard copy and the online version

![image](https://user-images.githubusercontent.com/6738800/94104879-64252100-fe38-11ea-9634-76a53234cd39.png)

**Comment by shokru** [comment]
Thank you very much for pointing this out.
I just corrected it. A very minor blip which causes a silly formatting issue.
