### ISSUE TITLE
Bayesianized p-Value

### ISSUE THREAD

**Issue by csrvermaak** [shokru/mlfactor.github.io#54]
In the example provided for equation (3.3), given the prior odds of 6, is it correct to infer that the researcher has put only a 14% probability of success on the factor being researched?

Odds of 6 = 0.86/(1-0.86), where probability p = 0.86, is the prior of the researcher of an 86% chance that the null holds (thus reject the hypothesis of a significant factor).

This translates to a 14% Bayesian prior for a successful factor?

**Comment by shokru** [comment]
Yes I think this is correct.
I strongly recommend reading the article of Harvey (_The Scientific Outlook in Financial Economics_).
It's one of the best I have read in the past 5 years. 
In the paper, he uses a 4:1 ratio for prior odds, which translates in a belief that the effect is true 20% of the time (Section 8, p23).
