### ISSUE TITLE
all_R_notebooks.zip - Chapter 3 missing

### ISSUE THREAD

**Issue by csrvermaak** [shokru/mlfactor.github.io#55]
The very useful `all_R_notebooks.zip` file doesn't contain the .Rmd for Chapter3.

**Comment by shokru** [comment]
I think it's because there is a shift in the chapter numbers. 
Chapter 3 in the book corresponds to chapter 4 in the notebooks. 
One chapter got zeroed by the editor...
I do need to change the names, you are right.

**Comment by shokru** [comment]
I think it's correct now. But you have to download the new version of the file.
