### ISSUE TITLE
Chapter 4.1 - spelling of "colinearities"

### ISSUE THREAD

**Issue by csrvermaak** [shokru/mlfactor.github.io#56]
Possible spelling issue: "colinearities" 

Beyond first order moments, second order quantities (variances and covariances/correlations) also matter because they help spot colinearities. When two features are highly correlated, problems may arise in some models (e.g., simple regressions, see Section 15.1).

The original `bookdown` codebase isn't available on GitHub, thus unable to submit pull requests.

**Comment by csrvermaak** [comment]
Actually, I see the use with a single "l" is also generally accepted. Closing the issue.

**Comment by shokru** [comment]
Yes, the original .Rmd code is not public. If you want to correct online (in html), you can do it directly. 
I will accept the change, then correct in Rmd so that when I re-generate the website, the new version is ok. 
I do this once a month, roughly...
