### ISSUE TITLE
Possible typos in chapters 3, 4, and 5

### ISSUE THREAD

**Issue by fayolle** [shokru/mlfactor.github.io#60]
These are possible typos that I found while going through the chapters 3 to 5: 
* Chapter 3 - factor.html:
  * "We obtain the vector of \alpha values from Equation ()."-> Equation (3.1) ? 
In http://www.mlfactor.com/factor.html#factor-competition
  * " and huang2020fundamental." -> problem with the bib. entry
* Chapter 4 - Data.html: 
  * Fig. 4.4 is missing. 
In http://www.mlfactor.com/Data.html#fig:triplebarrier
  * They report: “.”-> It seems that the reported sentence(s) is missing ?
In http://www.mlfactor.com/Data.html#labelling
* Chapter 5 - lasso.html: 
  * Just above (5.13): "Combining (), () and (), we get that the first line" -> (5.9), (5.11) and (5.12)? 
http://www.mlfactor.com/lasso.html#sparse-hedging-for-minimum-variance-portfolios
  * "If the allocation scheme has the form ()" [Missing equation number]
  * The end of 5.2.1 seems to have some issues:  
    - "then the pseudo-code for the sparse portfolio strategy is the following." but there is no pseudo-code
    - "At each date (which we omit for notational convenience), where we recall that the vectors ..." -> Some equations seem to be missing after "At each date" / before "where we recall"? 

If that helps, I can probably fix some of these typos in the .rmd files directly and create a PR with the updated .html. 
However, there are some for which I have no idea what the fix should be.

**Comment by shokru** [comment]
Thank you very much for spotting these issues/typos.
Some of them come from mixing LaTeX with markdown, which is ok for pdf export but less for html export...
I think I have solved all problems.
Tell me if I missed something!

**Comment by fayolle** [comment]
Thank you. 
I have never really tried to mix markdown and LaTeX. But I can imagine that it can go astray.
