### ISSUE TITLE
Possible typos in chapters 10, 11, 12

### ISSUE THREAD

**Issue by fayolle** [shokru/mlfactor.github.io#62]
* chapter 10: 
  * 10.1.1 Regression analysis
"Hence, the error is expressed in a percentage score and the averages are simply equal to:
where the latter can be scaled by a square root if need be."
The expression is missing after "to:" and before "where"
  * 10.2.1
"Given an unknown sample x, the decomposition of the average squared error is"
the expression for the decomposition is missing
  * 10.2.4
"to prevent the model from going to deep"
-> "to prevent the model from going too deep"
  * 10.3
"critical to choose each trial for b wisely."
-> p instead of b? 
  * 10.3 In (10.11), and just before, shouldn't it be p^{(m+1)} instead of p^{m+1}? 
Similarly in step 2b, 2c and 3? 

* chapter 11:
  * 11.1 "where while the second term converges to zero as M increases, the second term remains ... "
-> "... the first term remains ..."
  * 11.1 "constraint in the construction mean-variance allocations."
-> "... in the construction of mean-variance allocations." ? 

* chapter 12:
  * 12.2 
"The term $(w-w_{-}) \Lambda (w-w_{-})$ is an expression that characterizes ..."
-> The transpose is missing for the first term $(w-w_{-})' \Lambda (w-w_{-})$
  * The transpose is also missing in the expression of the Lagrangian (just after "Recalling that there are $N$ assets ...")
  * 12.2 The expression of the Lagrangian is overflowing 
(just after "Recalling that there are $N$ assets ...")
  * 12.3.2
There is an extra "=" in the geometric average $\tilde{\mu}_B$ 
(just after "above but the geometric one is also an option, in which case:")
  * 12.4 
Some text/equations are missing just after: 
"is the theoretical average maximum SR. Moreover,"
and before: 
"If t defined above is below a certain threshold ..."
  * 12.5 
The reference was not processed correctly in "In factor investing, there does not seem to be such invariance (see \cite(cornell2020stock))." 
I.e. "\cite" appears in the text.

**Comment by shokru** [comment]
Thanks a lot! (again!).
I think I was able to solve everything, except the overflowing, which is not a super big deal.
I'm getting more and more confident that the revised version of the book will almost be typo-free!
