### ISSUE TITLE
Possible typos in chapters 13, 14, 15, 16

### ISSUE THREAD

**Issue by fayolle** [shokru/mlfactor.github.io#63]
* chapter 13: 
  * In 13.2.1 LIME
In the expressions for the Euclidean and Manhattan distance, the index in the summand should be “n” instead of “i” 

* chapter 14: 
  * In 14.1.2
“dagitty (textor2016robust)” -> “dagitty \cite{textor2016robust}” ?
  * In 14.1.3 (Structural time series models)
The last 4 chapters of the sub-section are in italic (“During the post-intervention, … “)

* chapter 15:
  * In 15.2.1
Below (15.1): \Delta_{i,i} \geq 0 instead of “\Delta i,i \geq 0” 
  * In 15.2.2 (PCA)
“All of this is coded in the covariance matrix of Y“ -> In the covariance matrix of Z
  * In (15.4) and the text below, \Sigma_Y is used, but it should be \Sigma_Z 
  * In 15.2.3 (Autoencoder)
The first equation should be: Z = XP and X = ZP’
Below (15.6) “the recoding cannot recover P” -> “the recoding cannot recover X”
“see Proposition 1 in for the case of single layer autoencoders.” -> The reference is missing after “for”

* chapter 16: 
  * In 16 (Reinforcement Learning). 
Some of the references in the first paragraph are missing \cite: 
“Market microstructure is a focal framework (Wei et al. (2019), ferreira2020reinforced, karpe2020multi).” -> \cite{ferreira2020reinforced}, \cite{karpe2020multi}
  * In 16.1.2 (Q-learning), there is a bug in (16.8): “echo of (???)”. It should be an undefined \ref
  * In 16.1.3 (SARSA), “In expected SARSA, the average smoothes the learning process” -> “smooths”
  * In 16.2 (The curse of dimensionality), “The number of options for weight combinations is exponentially increasing N” -> “increasing with N”? 
  * In 16.3.2 (Extensions), there is a missing \cite (or \ref) in “see, e.g., section 2.3.1 in”

**Comment by shokru** [comment]
WOW! Thanks a lot (again)!
In chapter 14, yes, the final part is in italic on purpose because it's the output from the function call (we did not write it).
In chapter 15, I don't know why I included Y's all over the place.
If (when?) there is a second edition, it will much cleaner than the first one, in great part thanks to you!

**Comment by fayolle** [comment]
Thank you. It was a very nice read.
