### ISSUE TITLE
Chapter 12 codes

### ISSUE THREAD

**Issue by vitorying** [shokru/mlfactor.github.io#65]
Hi Shokru, 
I am trying to run the codes in Chapter 12 but got the following error. Can you please advice what is the issue?

![2021-03-31 220555](https://user-images.githubusercontent.com/60383122/113157604-a018c300-926d-11eb-9ae6-3d5c6d1ad5bc.png)

Thanks,
Victor

**Comment by shokru** [comment]
This usually occurs when the xgboost package is not loaded.
=> library(xgboost)
But it seems you figured it without my help!
