### ISSUE TITLE
2 small typos - chapter 2

### ISSUE THREAD

**Issue by ghost** [shokru/mlfactor.github.io#67]
![image](https://user-images.githubusercontent.com/48190318/116786197-a1702200-aa9d-11eb-8b3a-ce1cdc537ba4.png)

**Comment by shokru** [comment]
Agreed for the second.
But for the first, I'm using the idiom "make do", so I think it's grammatically correct.
I will make the change in the next update.
Thanks!

**Comment by ghost** [comment]
You are correct, apologies.
