### ISSUE TITLE
Possibly 2 small typos - chapter 3

### ISSUE THREAD

**Issue by ghost** [shokru/mlfactor.github.io#68]
![image](https://user-images.githubusercontent.com/48190318/116793249-f45dcf80-aac5-11eb-80d4-f247803aee47.png)
--> demonstrated 
![image](https://user-images.githubusercontent.com/48190318/116793281-2ff89980-aac6-11eb-926d-72701d53cca5.png)
--> researchers

**Comment by shokru** [comment]
Updated! Thanks again!
